PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS Clientes (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  nomeCliente TEXT NOT NULL,
  emailCliente TEXT
);

CREATE TABLE IF NOT EXISTS Compras (
  CompraID INTEGER PRIMARY KEY AUTOINCREMENT,
  ClienteID INTEGER NOT NULL,
  NomeLivro TEXT NOT NULL,
  FOREIGN KEY (ClienteID) REFERENCES Clientes(ID) ON DELETE CASCADE
);

COMMIT;
